version: '3'
services:
    server:
        build: .
        container_name: cpost_server
        command: flask run
        ports:
            - "3000:3000"
        networks:
            - network
        volumes:
            - ./src:/app
            - ./templates:/app/templates:ro
        environment:
            FLASK_APP: /app/routes.py
            FLASK_DEBUG: 1
            FLASK_RUN_HOST: 0.0.0.0
            FLASK_RUN_PORT: 3000
    db:
        image: mysql
        container_name: cpost_db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        ports:
            - "3306:3306"
        networks:
            - network
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: cpost
            MYSQL_USER: cpost_agent
            MYSQL_PASSWORD: ceskaposta
        volumes:
            - db_datavolume:/var/lib/mysql
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
    db_datavolume:

networks:
    network:
        driver: bridge

            
