version: '3'
services:
    agent:
        build: .
        container_name: cpost_agent
        command: python /app/run.py
        ports:
            - "3000:3000"
        volumes:
            - ./src:/app:ro
            - ./templates:/templates
        environment:
            FLASK_APP: routes.py
            FLASK_DEBUG: 1
    db:
        image: mysql
        container_name: cpost_db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: cpost
            MYSQL_USER: cpost_agent
            MYSQL_PASSWORD: ceskaposta
        volumes:
            - db_datavolume:/var/lib/mysql
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
    db_datavolume:

            
